### ISSUE TITLE
Niet-Windows compatiblity

### ISSUE THREAD

**Issue by MarcoDuiker** [Geonovum/dso_gio_qgis_plugin#1]
Op niet windows machines werkt deze plugi niet ivm 

```
import win32api
```

Dit vervangen door

```
try:
  import win32api
except:
  win32api = None
```

en dan verderop (2x) de volgende contsructie gebruiken lost dit op:

```
folder = os.path.dirname(fullPath)
if win32api:
          folder = win32api.GetShortPathName(folder)
```

**Comment by wilkoquak** [comment]
Hi Marco. Dit is een valide bugreport, er is momenteel alleen niemand om de plugin in beheer te nemen en ik ga het repository in de archiefstand zetten waarbij het gebruikelijk is om alle bugs te sluten
