### ISSUE TITLE
nummering GIO's bij filter en dissolve en losse gio's

### ISSUE THREAD

**Issue by MarcoDuiker** [Geonovum/dso_gio_qgis_plugin#2]
Bij het samennemen van features op een attribuut, en dan uitsplitsen over losse gio's ontstaan oplopen genummerde  FRBR expressions.

Het lijkt logischer om hiervoor het attribut te nemen waarop wordt samengevoegd.

Dit kan door 

```
self.catExpression(FRBRList, item6, number)
```

te vervanger door

```
self.catExpression(FRBRList, item6, self.dlg.attribuutwaardelijst.currentText())
```

**Comment by wilkoquak** [comment]
Hi Marco. Dit is een valide issue, er is momenteel alleen niemand om de plugin in beheer te nemen en ik ga het repository in de archiefstand zetten waarbij het gebruikelijk is om alle issues te sluten.
