### ISSUE TITLE
Meer dan 3 decimalen

### ISSUE THREAD

**Issue by MarcoDuiker** [Geonovum/dso_gio_qgis_plugin#3]
Bij het samennemen van features op een attribuut, en dan uitsplitsen over losse gio's ontstaan geometrieen met meer dan 3 decimalen.

**Comment by wilkoquak** [comment]
Hi Marco. Dit is een valide bugreport, er is momenteel alleen niemand om de plugin in beheer te nemen en ik ga het repository in de archiefstand zetten waarbij het gebruikelijk is om alle bugs te sluten
